name: Basic Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  hello:
    name: Basic Hello World
    runs-on: ubuntu-latest

    steps:
      - name: Hello
        run: echo "Hello from GitHub Actions"
      - name: Check OS
        run: uname -a
      - name: Status
        run: echo "Workflows in this repo should now work"
